/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
    application
}

repositories {
    mavenCentral()
}
dependencies {
    // https://mvnrepository.com/artifact/log4j/log4j
    implementation("log4j:log4j:1.2.16")
}
application {
    mainClass.set("com.ul.Main")
}
